#!/bin/bash
TS3_HOME="/opt/teamspeak3-server"

export LD_LIBRARY_PATH="${TS3_HOME}:${TS3_HOME}/redist:$LD_LIBRARY_PATH"

cd ${TS3_HOME}
sed -i "s|^database=.*|database=${TS3_DATABASE}|g" ts3db_mariadb.ini
./ts3server_linux_amd64 inifile=${TS3_HOME}/ts3server.ini

